class StaticPagesController < ApplicationController

#'home' and 'help' are methods generated by the rails command
#They 'serve' the views home.html.erb and help.html.erb
  def home
  end

  def help
  end

  def about
  end
end
