class StaticPagesController < ApplicationController

#'home' and 'help' are methods generated by the rails command
#They 'serve' the views home.html.erb and help.html.erb
  def home
    if signed_in?
      @minituit   = current_user.minituits.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end
